# Generated by Django 4.2.21 on 2025-09-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta mascota', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Vacunador principal asignado (compatibilidad)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Técnico principal asignado', limit_choices_to={'tipo_usuario': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planillas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tecnicos_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Técnicos adicionales asignados', limit_choices_to={'tipo_usuario': 'tecnico'}, related_name='planillas_como_tecnico_adicional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='vacunadores_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Vacunadores adicionales asignados', limit_choices_to={'tipo_usuario': 'vacunador'}, related_name='planillas_como_vacunador_adicional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vacunador', 'Vacunador'), ('tecnico', 'Técnico')], default='vacunador', help_text='Tipo de usuario en el sistema', max_length=20),
        ),
    ]
