# Generated by Django 4.2.21 on 2025-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mascota_created_by_alter_planilla_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, help_text='Indica si la mascota está esterilizada'),
        ),
    ]
