# Generated by Django 4.2.21 on 2025-05-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mascota_planilla_veterinario_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='api.veterinario'),
        ),
    ]
