# Generated by Django 4.2.21 on 2025-05-22 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_planilla_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilla',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to=settings.AUTH_USER_MODEL),
        ),
    ]
