# Generated by Django 5.1.4 on 2025-09-07 01:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mascota_esterilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de vacunas perdidas')),
                ('lote_vacuna', models.CharField(help_text='Número de lote de las vacunas perdidas', max_length=100)),
                ('motivo', models.TextField(blank=True, help_text='Motivo de la pérdida (opcional)', null=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto de evidencia (opcional)', null=True, upload_to='perdidas/%Y/%m/%d/')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud GPS', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud GPS', max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del registro')),
                ('fecha_perdida', models.DateField(default=django.utils.timezone.now, help_text='Fecha cuando ocurrió la pérdida')),
                ('sincronizado', models.BooleanField(default=False, help_text='Indica si ya fue sincronizado con el servidor')),
                ('uuid_local', models.CharField(blank=True, help_text='UUID generado localmente para sincronización', max_length=100, null=True)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró la pérdida', on_delete=django.db.models.deletion.CASCADE, related_name='perdidas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Pérdida',
                'verbose_name_plural': 'Registros de Pérdidas',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['-fecha_registro'], name='api_registr_fecha_r_81459c_idx'), models.Index(fields=['lote_vacuna'], name='api_registr_lote_va_b75506_idx'), models.Index(fields=['registrado_por'], name='api_registr_registr_27d108_idx')],
            },
        ),
    ]
