# Generated by Django 4.2.21 on 2025-08-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_planilla_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='creada',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='planilla',
        ),
        migrations.AddField(
            model_name='mascota',
            name='antecedente_vacunal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(default='Sin especificar', max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='perro', max_length=10),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('finca', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='api.planilla')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='api.responsable'),
        ),
    ]
