# Generated by Django 4.2.21 on 2025-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_creada_mascota_creado_remove_mascota_planilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la mascota', null=True, upload_to='mascotas/fotos/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitud de la ubicación de la mascota', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitud de la ubicación de la mascota', max_digits=11, null=True),
        ),
    ]
