# Generated by Django 4.2.21 on 2025-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_mascota_latitud_alter_mascota_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitud de la ubicación de la mascota', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitud de la ubicación de la mascota', max_digits=15, null=True),
        ),
    ]
