# Generated by Django 4.2.21 on 2025-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_mascota_latitud_alter_mascota_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='centro_poblado_vereda_barrio',
            field=models.CharField(default='Sin especificar', help_text='Centro poblado, vereda o barrio', max_length=100),
        ),
        migrations.AddField(
            model_name='planilla',
            name='municipio',
            field=models.CharField(default='Sin especificar', help_text='Nombre del municipio', max_length=100),
        ),
        migrations.AddField(
            model_name='planilla',
            name='urbano_rural',
            field=models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural')], default='urbano', help_text='Tipo de zona: urbano o rural', max_length=10),
        ),
        migrations.AddField(
            model_name='planilla',
            name='zona',
            field=models.CharField(default='Sin especificar', help_text='Zona específica', max_length=100),
        ),
    ]
