# Generated by Django 4.2.21 on 2025-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_planilla_centro_poblado_vereda_barrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='lote_vacuna',
            field=models.CharField(default='Sin especificar', help_text='Lote de la vacuna utilizada', max_length=50),
        ),
        migrations.AddField(
            model_name='responsable',
            name='nombre_zona',
            field=models.CharField(default='Sin especificar', help_text='Nombre descriptivo de la zona', max_length=150),
        ),
        migrations.AddField(
            model_name='responsable',
            name='zona',
            field=models.CharField(default='Sin especificar', help_text='Zona específica de vacunación', max_length=100),
        ),
    ]
