# Generated by Django 4.2.7 on 2025-08-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_tipo_usuario_and_tecnico_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('vacunador', 'Vacunador'), ('tecnico', 'Técnico')], default='vacunador', help_text='Tipo de usuario: administrador, vacunador o técnico', max_length=15, null=True),
        ),
    ]
