# Generated by Django 4.2.7 on 2025-08-16 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_veterinario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='tecnicos_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Técnicos adicionales asignados para revisar esta planilla', limit_choices_to={'tipo_usuario': 'tecnico'}, related_name='planillas_como_tecnico_adicional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planilla',
            name='vacunadores_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Vacunadores adicionales asignados a esta planilla', limit_choices_to={'tipo_usuario': 'vacunador'}, related_name='planillas_como_vacunador_adicional', to=settings.AUTH_USER_MODEL),
        ),
    ]
